src/BaseFirestoreRepository.spec.ts
src/BaseFirestoreRepository.ts
src/QueryBuilder.ts
src/types.ts

Implemented limit feature

---

package.json
src/BaseFirestoreRepository.spec.ts
src/BaseFirestoreRepository.ts
src/MetadataStorage.ts
src/helpers.spec.ts
src/helpers.ts
src/types.ts
test/fixture.ts
yarn.lock

Returning class instances from methods so models can have getters!

Returning class instance from methods

---

.travis.yml
README.md
package.json
yarn.lock

WIP: Chore: Setup semantic-release

---

.travis.yml
README.md
package.json
src/types.ts
yarn.lock

- Added documentation to semantic release
- Added commitlint to lint commit messages
- Limiting files to be packaged

fix: automated deployment!

---

.travis.yml
package.json
yarn.lock

- Dependencies up to date
- Added 'Build Documentation' step to travis
- Added incremental flag to tsc for faster builds when developing

Chore: build enhancements

---

.vscode/launch.json
package.json
src/BaseFirestoreRepository.spec.ts
test/fixture.ts
yarn.lock

Test: Adding Subcollection's CRUD tests

---

src/BaseFirestoreRepository.spec.ts
src/BaseFirestoreRepository.ts

 fix: initializing subcollection on create

---

README.md
package.json
yarn.lock

docs: adding reflect-metadata instructions in README

---

src/AbstractFirestoreRepository.ts
src/BaseFirestoreRepository.spec.ts
src/BaseFirestoreRepository.ts
src/QueryBuilder.ts
src/types.ts
test/functional/1-simple_repository.spec.ts

Closes #89.
~~Unit and integration tests are not done yet, but I'm going to give it a shot. Reviews welcome, please.~~

Implement findOne operation

---

src/AbstractFirestoreRepository.ts
src/BaseFirestoreRepository.spec.ts
src/types.ts
test/BandCollection.ts
test/fixture.ts
test/functional/1-simple_repository.spec.ts
test/functional/5-document-references.spec.ts
test/functional/6-validations.spec.ts
test/setup.ts
yarn.lock

Feature: document references in where methods

---

src/AbstractFirestoreRepository.ts
src/BaseFirestoreRepository.spec.ts
src/BaseFirestoreRepository.ts
src/BaseFirestoreTransactionRepository.spec.ts
src/BaseFirestoreTransactionRepository.ts
src/MetadataStorage.ts
src/helpers.spec.ts
src/helpers.ts
src/types.ts
test/BandCollection.ts
test/fixture.ts

Sub-collections are currently only being initialised one level deep. This PR fixes this to allow subcollections to have subcollections

fix: fix nested subcollection initialization

---

src/AbstractFirestoreRepository.ts
src/BaseFirestoreRepository.spec.ts

fix: fetching entity w/o id within firestore doc

---

src/AbstractFirestoreRepository.ts
src/Batch/BaseFirestoreBatchRepository.ts
src/Batch/FirestoreBatchUnit.ts
src/Errors/ValidationError.ts

fix: copying ValidationError from class-validator to prevent error

---

README.md

I've just detected a wrong link, so I've fixed it.

docs: geoPoints spec link fix

---

docgen/Custom_Repositories.md
docgen/Read_Data.md
src/AbstractFirestoreRepository.ts
src/BaseFirestoreRepository.spec.ts
src/QueryBuilder.spec.ts
src/QueryBuilder.ts
src/Transaction/BaseFirestoreTransactionRepository.spec.ts
src/types.ts
test/functional/1-simple_repository.int-spec.ts

Work done by @LukaszKuciel.
Just added documentation and integration tests.

Feature: adding array in and in operators

---

package.json
src/MetadataStorage.ts
src/Transaction/BaseFirestoreTransactionRepository.spec.ts
src/Transaction/BaseFirestoreTransactionRepository.ts
src/tsconfig.json

This PR is a first attempt on #161. It adds a `tsconfig.json` in the `src` folder so we can make the migration incrementally (will be removed after finishing the migration). In this first part we are only checking the `Decorators` folder and its dependencies.

chore: strict rules pt. 1

---

src/BaseFirestoreRepository.ts
src/Batch/FirestoreBatch.ts
test/functional/3-subcollections.int-spec.ts

Hi, @skalashnyk asked me to help him with the issue #183. I fixed that problem, and added the case to the tests.

fix: wovalle#183 batch write within subcollection

---

src/types.ts

fix: improve the update method types following the method functional logic

fix: improve the update method types

---

docgen/Subcollections.md

docs: adding documentation for nested subcollections

---

README.md

docs: add commit types

---

src/types.ts

feat: allow querying null fields

---

package.json
yarn.lock

fix: lock class transformer version
